{% set name = "txl-remote-kernels" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/txl_remote_kernels-{{ version }}.tar.gz
  sha256: 8ad509068e33eb2531203f864e041bf771277752b06e4f01ae048179b0c7e8c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - txl
    - txl-kernel
    - httpx >=0.23.1
    - httpx-ws >=0.4.2
    - pycrdt >=0.8.11,<0.9.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl_remote_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  summary: TXL plugin for remote kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
