{% set python_min = "3.10" %}
{% set name = "txl-remote-kernels" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_remote_kernels-{{ version }}.tar.gz
  sha256: 017c67529ba94c60260b12f35b5f3e04c34d359c6b9abfc4a573fdc5c6769850

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2
    - txl-kernel
    - httpx >=0.23.1
    - httpx-ws >=0.4.2
    - pycrdt >=0.10.9,<0.13.0

test:
  requires:
    - pip
  commands:
    - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_remote_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  summary: TXL plugin for remote kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
