{% set python_min = "3.10" %}
{% set name = "txl-remote-kernels" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_remote_kernels-{{ version }}.tar.gz
  sha256: d459c37f90572228f4ca1978842ecf184d0e95d40a75422f334549aa62b44760

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - txl-kernel
    - httpx >=0.23.1
    - httpx-ws >=0.4.2
    - pycrdt >=0.10.9,<0.11.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_remote_kernels

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  summary: TXL plugin for remote kernels
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/remote_kernels
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
